### ISSUE TITLE
Can't connect

### ISSUE THREAD

**Issue by samuelpares** [OSLC/oslc-client#30]
Hi, guys! 
I'm new to OSLC.. trying to use this lib for RTC.
I'm following the updateCR.js sample, but I'm having an issue on connect():

I create the server:
```
var server = new OSLCServer(args.iparams.server_uri, args.iparams.user_id, args.iparams.user_password);
console.log(server)
```

```
OSLCServer {
  serverURI: 'https://ommited:9443/ccm',
  userId: 'samuel',
  password: 'samuel',
  rootservices: null,
  serviceProviderCatalog: null,
  serviceProviderTitle: null,
  serviceProvider: null }
```

When I call connect:
`server.connect(OSLCCM10("cmServiceProviders"), callback),`

I get:

```
TypeError: Cannot read property 'uri' of null
    at OSLCServer.read (/home/samuel/workspace/fdk/freshdesk/server/node_modules/oslc-client/server.js:184:48)
    at gotRootServices (/home/samuel/workspace/fdk/freshdesk/server/node_modules/oslc-client/server.js:103:9)
    at gotResult (/home/samuel/workspace/fdk/freshdesk/server/node_modules/oslc-client/server.js:205:3)
    at Request._callback (/home/samuel/workspace/fdk/freshdesk/server/node_modules/oslc-client/oslcRequest.js:74:4)
    at Request.self.callback (/home/samuel/workspace/fdk/freshdesk/server/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/home/samuel/workspace/fdk/freshdesk/server/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (/home/samuel/workspace/fdk/freshdesk/server/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```
What am I missing here?

**Comment by jamsden** [comment]
Looks like your server doesn't have any cmServiceProviders. Check the https://ommited:9443/ccm/rootservices resource.

**Comment by samuelpares** [comment]
I think there is:

```
<?xml version="1.0"?>

<!--
    Licensed Materials - Property of IBM
    © Copyright IBM Corporation 2010, 2018. All Rights Reserved.
    
    Note to U.S. Government Users Restricted Rights:  
    Use, duplication or disclosure restricted by GSA ADP Schedule 
    Contract with IBM Corp. 
 -->

<rdf:Description
     xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
     xmlns:dc="http://purl.org/dc/terms/"
     xmlns:jfs="http://jazz.net/xmlns/prod/jazz/jfs/1.0/" 
     xmlns:jd="http://jazz.net/xmlns/prod/jazz/discovery/1.0/"
     xmlns:jdb="http://jazz.net/xmlns/prod/jazz/dashboard/1.0/"
     xmlns:jp06="http://jazz.net/xmlns/prod/jazz/process/0.6/"
     xmlns:jp="http://jazz.net/xmlns/prod/jazz/process/1.0/"
     xmlns:jtp="http://jazz.net/xmlns/prod/jazz/jtp/0.6/"
     xmlns:ju="http://jazz.net/ns/ui#"
     xmlns:oslc="http://open-services.net/ns/core#"
     xmlns:trs="http://jazz.net/ns/trs#"
	 xmlns:trs2="http://open-services.net/ns/core/trs#"
	 xmlns:lqe="http://jazz.net/ns/lqe#"
     rdf:about="https://localhost:9443/ccm/rootservices">

  <!-- 
  		Default root service registry document for an RTC server.
  		Contains contributions for core JFS services and components
  		and OSLC Change Management.
  		Specification is available at https://jazz.net/wiki/bin/view/Main/RootServicesSpec
   -->

  <!-- Add descriptive title here -->
  <dc:title xml:lang="en">Change and Configuration Management</dc:title>

  <!-- List of friends (applications known to this application) -->
  <jd:friends
      rdf:resource="https://localhost:9443/ccm/friends" />
       
  <!-- Discovery service for the JFS server and associated applications -->
  <jd:discovery
      rdf:resource="https://localhost:9443/ccm/discovery" />
       
  <!-- Viewlet-related properties -->
  <jd:viewletServiceRoot
  	  rdf:resource="https://localhost:9443/ccm" />

  <jd:viewletWebUIRoot
  	  rdf:resource="https://localhost:9443/ccm" />

  <!-- Default root service registry document for a JFS server. -->

  <jd:jsaSsoEnabled>false</jd:jsaSsoEnabled>

  <jfs:oauthRequestTokenUrl
  	  rdf:resource="https://localhost:9443/ccm/oauth-request-token" />
  
  <jfs:oauthAccessTokenUrl
  	  rdf:resource="https://localhost:9443/ccm/oauth-access-token" />
  	  
  <jfs:oauthRealmName>Jazz</jfs:oauthRealmName>
  <jfs:oauthDomain>https://localhost:9443/ccm</jfs:oauthDomain>
  	  
  <jfs:oauthUserAuthorizationUrl
  	  rdf:resource="https://localhost:9443/ccm/oauth-authorize" />
  	  
  <jfs:oauthRequestConsumerKeyUrl
      rdf:resource="https://localhost:9443/ccm/oauth-request-consumer" />
      
  <jfs:oauthApprovalModuleUrl
      rdf:resource="https://localhost:9443/ccm/_ajax-modules/com.ibm.team.repository.AuthorizeOAuth" />	  
  
  <!-- JAuth URLS -->
  
  <jfs:jauthIssueTokenUrl
      rdf:resource="https://localhost:9443/ccm/jauth-issue-token" />
      
  <jfs:jauthCheckTokenUrl
      rdf:resource="https://localhost:9443/ccm/jauth-check-token" />
      
  <jfs:jauthRevokeTokenUrl
      rdf:resource="https://localhost:9443/ccm/jauth-revoke-token" />
      
  <jfs:jauthCheckAuthUrl
      rdf:resource="https://localhost:9443/ccm/jauth-check-auth" />
      
  <jfs:jauthProxyUrl
      rdf:resource="https://localhost:9443/ccm/jauth-proxy" />
      
  <!-- service for finding users and getting user info -->
  <jfs:users
  	  rdf:resource="https://localhost:9443/jts/users"   />
  
  <!-- Service to redirect to the resource that represents the authenticated user -->
  <jfs:currentUser
  	  rdf:resource="https://localhost:9443/ccm/whoami"   />
  	  
  <!-- JFS storage service --> 
  <jfs:storage
  	  rdf:resource="https://localhost:9443/ccm/storage"   />
  
  <!-- JFS SPARQL query service -->
  <jfs:query
  	  rdf:resource="https://localhost:9443/ccm/query"   />

  <!-- Put RTC changes in here, so we do not have to merge all the time : START -->

  <!-- Change Management service catalog -->
  <oslc_cm:cmServiceProviders
	      xmlns:oslc_cm="http://open-services.net/xmlns/cm/1.0/"
	      rdf:resource="https://localhost:9443/ccm/oslc/workitems/catalog" />
	      
  <oslc_config:cmServiceProviders
	      xmlns:oslc_config="http://open-services.net/ns/config#"
	      rdf:resource="https://localhost:9443/ccm/rtcoslc/catalog" />
	      
  <oslc_scm:scmServiceProviders
	      xmlns:oslc_scm="http://open-services.net/xmlns/scm/1.0/"
	      rdf:resource="https://localhost:9443/ccm/oslc-scm/catalog" />
	      
  <jd:oslcCatalogs>
		<oslc:ServiceProviderCatalog rdf:about="https://localhost:9443/ccm/oslc/workitems/catalog">
			<oslc:domain rdf:resource="http://open-services.net/ns/cm#"/>
    	</oslc:ServiceProviderCatalog>
  </jd:oslcCatalogs>

  <jd:oslcCatalogs>
		<oslc:ServiceProviderCatalog rdf:about="https://localhost:9443/ccm/oslc-scm/catalog">
			<oslc:domain rdf:resource="http://open-services.net/ns/scm#"/>
		</oslc:ServiceProviderCatalog>
  </jd:oslcCatalogs>
  
  <!-- Change Management Tracked Resource Set 1.0 Provider -->
  <rtc_cm:trackedResourceSetProvider xmlns:rtc_cm="http://jazz.net/xmlns/prod/jazz/rtc/cm/1.0/">
  		<trs:TrackedResourceSetProvider>
			<trs:trackedResourceSet rdf:resource="https://localhost:9443/ccm/oslc/workitems/trs" />
			<dc:title>RTC Tracking and Planning Resources (TRS 1.0)</dc:title>
			<dc:description>Rational Team Concert (CCM) tracking and planning resources, including work items, plans, and releases.</dc:description>
			<dc:type     rdf:resource="http://open-services.net/ns/cm#" />
			<oslc:domain rdf:resource="http://open-services.net/ns/cm#" />			
			<oslc:domain rdf:resource="http://open-services.net/ns/config#" />			
  		</trs:TrackedResourceSetProvider>
 </rtc_cm:trackedResourceSetProvider>
 
   <!-- Change Management Tracked Resource Set 2.0 Provider -->
  <rtc_cm:trackedResourceSetProvider xmlns:rtc_cm="http://jazz.net/xmlns/prod/jazz/rtc/cm/1.0/">
  		<trs2:TrackedResourceSet>
			<trs2:trackedResourceSet rdf:resource="https://localhost:9443/ccm/oslc/workitems/trs2" />
			<dc:title>RTC Tracking and Planning Resources (TRS 2.0)</dc:title>
			<dc:description>Rational Team Concert (CCM) tracking and planning resources, including work items, plans, and releases.</dc:description>
			<dc:type     rdf:resource="http://open-services.net/ns/cm#" />
			<lqe:diagnostic rdf:resource="https://localhost:9443/ccm/admin#action=jazz.viewPage&amp;id=com.ibm.team.rtc.reports.diagnostics" />
			<oslc:domain rdf:resource="http://open-services.net/ns/cm#" />			
			<oslc:domain rdf:resource="http://open-services.net/ns/config#" />			
  		</trs2:TrackedResourceSet>
  </rtc_cm:trackedResourceSetProvider>
  
  <!--  Process Component Tracked Resource Set 2.0 Provider -->
  <rtc_cm:trackedResourceSetProvider xmlns:rtc_cm="http://jazz.net/xmlns/prod/jazz/rtc/cm/1.0/">
	<trs2:TrackedResourceSet>
		<trs2:trackedResourceSet rdf:resource="https://localhost:9443/ccm/process-trs2" />
		<dc:title>RTC Process Resources (TRS 2.0)</dc:title>
		<dc:description>Rational Team Concert (CCM) process resources, including project areas and team areas.</dc:description>
		<dc:type     rdf:resource="http://jazz.net/ns/process#" />
		<oslc:domain rdf:resource="http://jazz.net/ns/process#" />
	</trs2:TrackedResourceSet>
  </rtc_cm:trackedResourceSetProvider>
  
  <!--  SCM Component Tracked Resource Set 2.0 Provider -->
  <rtc_cm:trackedResourceSetProvider xmlns:rtc_cm="http://jazz.net/xmlns/prod/jazz/rtc/cm/1.0/">
	<trs2:TrackedResourceSet>
		<trs2:trackedResourceSet rdf:resource="https://localhost:9443/ccm/rtcoslc/scm/reportable/trs/cs" />
		<dc:title>RTC SCM Change Sets (TRS 2.0)</dc:title>
		<dc:description>Rational Team Concert (CCM) source control management change sets.</dc:description>
		<dc:type     rdf:resource="http://jazz.net/ns/scm#" />
		<lqe:diagnostic rdf:resource="https://localhost:9443/ccm/admin#action=jazz.viewPage&amp;id=com.ibm.team.rtc.reports.diagnostics" />
		<oslc:domain rdf:resource="http://jazz.net/ns/scm#" />
	</trs2:TrackedResourceSet>
  </rtc_cm:trackedResourceSetProvider>
  <rtc_cm:trackedResourceSetProvider xmlns:rtc_cm="http://jazz.net/xmlns/prod/jazz/rtc/cm/1.0/">
	<trs2:TrackedResourceSet>
		<trs2:trackedResourceSet rdf:resource="https://localhost:9443/ccm/rtcoslc/scm/cslink/trs" />
		<dc:title>RTC SCM Change Set Link Resources (TRS 2.0)</dc:title>
		<dc:description>Rational Team Concert (CCM) source control management links between change sets and work items.</dc:description>
		<dc:type     rdf:resource="http://jazz.net/ns/scm#" />
		<lqe:diagnostic rdf:resource="https://localhost:9443/ccm/admin#action=jazz.viewPage&amp;id=com.ibm.team.rtc.reports.diagnostics" />
		<oslc:domain rdf:resource="http://jazz.net/ns/scm#" />
	</trs2:TrackedResourceSet>
  </rtc_cm:trackedResourceSetProvider>

	      
  <jd:registration
     rdf:resource="https://localhost:9443/ccm/service/com.ibm.team.repository.service.internal.setup.IRegistrationHandlerService" />
     
   <jfs:setupWizardDescriptor
     rdf:resource="https://localhost:9443/ccm/service/com.ibm.team.repository.service.internal.setup.ISetupWizardDescriptorService"/>
     
   <jfs:adminWebUI rdf:resource="https://localhost:9443/ccm/admin"/>

  <!-- Put RTC changes in here, so we do not have to merge all the time : END -->
  
  <!-- JFS indexing service --> 
  <jfs:indexing
  	  rdf:resource="https://localhost:9443/ccm/indexing"   />
  	  
  <!-- JFS revisions and history of storage resources -->  	  
  <jfs:history
  	  rdf:resource="https://localhost:9443/ccm/history"   />
  
  <!-- JFS full text search -->
  <jfs:search
  	  rdf:resource="https://localhost:9443/ccm/search"   />

  <!-- JFS baseline service --> 
  <jfs:baselines
  	  rdf:resource="https://localhost:9443/ccm/baselines"   />
  	  
  <!-- JFS mailer service --> 
  <jfs:mailer
  	  rdf:resource="https://localhost:9443/ccm/mailer"   />   	 
  
    <!-- JFS bulk operations service --> 
  <jfs:bulkOperations
  	  rdf:resource="https://localhost:9443/ccm/bulk"   />
  
  <!-- JFS changes service -->
  <jfs:changes
      rdf:resource="https://localhost:9443/ccm/changes" />
  
  <!-- Dashboards service (provisional) -->
  <jdb:dashboards
  	  rdf:resource="https://localhost:9443/ccm/dashboards" />  	 

  <!-- Widget Catalog -->    
  <ju:widgetCatalog
      rdf:resource="https://localhost:9443/ccm/jfs/WidgetCatalog"/>
  
  <!-- Web Welcome -->     
  <jd:infocenterRoot 
      rdf:resource="https://localhost:9443/ccm/../clmhelp" />
  
  <!-- Project areas service. This service is provisional and may change in the next release. -->
  <jp06:projectAreas
  	  rdf:resource="https://localhost:9443/ccm/process/project-areas" />

  <!-- Process templates service. This service is provisional and may change in the next release. -->
  <jp06:processTemplates
  	  rdf:resource="https://localhost:9443/ccm/process/templates" />

  <!-- Process security service. This service is provisional and may change in the next release. -->
  <jp06:processSecurity 
      rdf:resource="https://localhost:9443/ccm/process-security"/>
    
  <!-- Process about service. It returns information about process and component versions without 
       requiring user authentication. See work item 236627 for details-->  
  <jp06:processAbout
  	  rdf:resource="https://localhost:9443/ccm/process-about" />
				
  <!-- Project Area Management for registered applications. This entry is provisional. -->
  <jp:manageProjectAreas 
        rdf:resource="https://localhost:9443/ccm/process/manageProjectAreas"/>

  <!-- Process Template Management for registered applications. This entry is provisional. -->
  <jp:manageProcessTemplates 
        rdf:resource="https://localhost:9443/ccm/process/manageProcessTemplates"/>

  <jtp:associations
      rdf:resource="https://localhost:9443/ccm/process-authoring/associations"/>
  
  <jtp:defaultPracticeLibraryUrl
      rdf:resource="https://localhost:9443/ccm/process-authoring/libraries/shared"/>
  
  <jtp:file
      rdf:resource="https://localhost:9443/ccm/process-authoring/file"/>
  
  <jtp:license
      rdf:resource="https://localhost:9443/ccm/process-authoring/license"/>
  
  <jtp:practices
      rdf:resource="https://localhost:9443/ccm/process-authoring/practices"/>
  
  <jtp:processDescriptions
      rdf:resource="https://localhost:9443/ccm/process-authoring/descriptions"/>
  
  <!-- Application about service. -->
  <oslc:publisher rdf:resource="https://localhost:9443/ccm/application-about"/>	  
  	  
  <!-- Server Rename Application Status service -->
  <jfs:serverRenameStatus
      rdf:resource="https://localhost:9443/ccm/appServerRenameStatus"/>
  	  
</rdf:Description>
```

**Comment by samuelpares** [comment]
I actually managed to read and create work items without this lib... but I would like to use it since it makes the work easier!

**Comment by samuelpares** [comment]
I fount out what the problem was!
RTC is running on windows, I was making the api call from a node app running on WSL.
Running everything on Windows, solved the problem.
